import { useEffect, useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { deleteNewsPost, getNewsPosts, saveNewsPost } from "../../../services/newsService";

const EMPTY_POST = { title: "", excerpt: "" };
const ManageNews = () => {
  const [posts, setPosts] = useState([]); const [form, setForm] = useState(EMPTY_POST); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState("");
  const loadPosts = async () => { try { setPosts(await getNewsPosts()); } catch { setMessage("Run the Gallery & News SQL setup in Supabase to manage news."); } finally { setLoading(false); } };
  useEffect(() => { loadPosts(); }, []);
  const submit = async (event) => { event.preventDefault(); setSaving(true); setMessage(""); try { await saveNewsPost({ title: form.title.trim(), excerpt: form.excerpt.trim() }); setForm(EMPTY_POST); await loadPosts(); setMessage("News post published."); } catch (error) { setMessage(error.message || "Could not publish this news post."); } finally { setSaving(false); } };
  const remove = async (post) => { if (!window.confirm(`Delete “${post.title}”?`)) return; try { await deleteNewsPost(post.id); await loadPosts(); } catch (error) { setMessage(error.message || "Could not delete this news post."); } };
  return <div className="mx-auto max-w-6xl"><div className="mb-8"><h1 className="font-heading text-2xl font-bold text-textPrimary">News Posts</h1><p className="mt-2 font-body text-sm text-textSecondary">Publish school announcements and remove them when they are no longer relevant.</p></div><div className="grid gap-8 xl:grid-cols-[.85fr_1.15fr]"><form onSubmit={submit} className="rounded-2xl border border-border bg-surface p-6 shadow-sm"><h2 className="font-heading text-lg font-semibold text-textPrimary">Add news</h2><label className="mt-5 block"><span className="font-body text-sm font-medium text-textPrimary">Headline</span><input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 font-body text-sm outline-none focus:ring-2 focus:ring-primary" /></label><label className="mt-5 block"><span className="font-body text-sm font-medium text-textPrimary">Summary</span><textarea required rows="6" value={form.excerpt} onChange={(e) => setForm({ ...form, excerpt: e.target.value })} className="mt-1.5 w-full rounded-xl border border-border px-3 py-2.5 font-body text-sm outline-none focus:ring-2 focus:ring-primary" /></label><button disabled={saving} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 font-body text-sm font-semibold text-white hover:bg-primaryDark disabled:opacity-60"><Plus className="h-4 w-4" />{saving ? "Publishing..." : "Publish news"}</button>{message && <p className="mt-4 font-body text-sm text-textSecondary" role="status">{message}</p>}</form><section className="rounded-2xl border border-border bg-surface p-6 shadow-sm"><h2 className="font-heading text-lg font-semibold text-textPrimary">Published news</h2>{loading ? <p className="mt-5 font-body text-sm text-textSecondary">Loading news...</p> : <div className="mt-5 space-y-3">{posts.length ? posts.map((post) => <article key={post.id} className="flex items-start justify-between gap-4 rounded-xl border border-border p-4"><div><h3 className="font-heading font-semibold text-textPrimary">{post.title}</h3><p className="mt-1 font-body text-sm text-textSecondary">{post.excerpt}</p></div><button type="button" onClick={() => remove(post)} className="rounded-lg p-2 text-red-600 hover:bg-red-50" aria-label={`Delete ${post.title}`}><Trash2 className="h-4 w-4" /></button></article>) : <p className="font-body text-sm text-textSecondary">No published news yet.</p>}</div>}</section></div></div>;
};
export default ManageNews;
